name: BSpawn
version: '${project.version}'
main: net.earthmc.bspawn.Main
api-version: '1.19'
dependencies:
  - name: Towny
    required: true
authors: [Fruitloopins]
description: Adds a cost to toggling and maintaining a public /t spawn in Towny.
website: https://earthmc.net
