name: BSpawn
version: "${project.version}"
main: net.earthmc.bspawn.BSpawn
api-version: "1.19"
dependencies:
  - name: Towny
    required: true
authors: [Fruitloopins]
description: Allow players to pay to allow outsiders to spawn
website: https://earthmc.net
folia-supported: true

permissions:
  bspawn.command.town.toggle.outsiderscanspawn:
    description: Grants permission to use the outsiderscanspawn command
    default: false
